### ISSUE TITLE
Migrate plugin to built-in Kotlin

### ISSUE THREAD

**Issue by kuteoalor** [appmetrica/appmetrica-flutter-plugin#27]
I am using appmetrica_plugin in my Flutter app.

Starting with Android Gradle Plugin (AGP) 9.0,
support for applying the Kotlin Gradle Plugin (KGP) has been removed.
Because this plugin applies KGP,
it causes a compilation error that prevents my app from building.
Flutter [issue #181383](https://github.com/flutter/flutter/issues/181383)
includes an example of the error.

Flutter has temporarily added support to allow KGP
while apps and plugins migrate to AGP 9.0 or later,
but this support will be removed in a future version of Flutter.

Please migrate this plugin to use built-in Kotlin to
ensure your plugin users can successfully
build their apps in future versions of Flutter.

Here is the Flutter
[migration guide for plugin authors](https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin/for-plugin-authors).

**Comment by KondratyonokNikita** [comment]
Hello. Thank you for your message. We don’t use Kotlin in the plugin. I’ve created a task ([internal link](https://nda.ya.ru/t/dDByMrXK7pH9JT)) double‑check the correctness of the work with the new AGP.

**Comment by KondratyonokNikita** [comment]
Hello! I’ve updated the versions in the integration example. Everything is working, and no changes were needed in the plugin. The example now builds with AGP 9.1.0 and Gradle 9.3.1.

If you encounter any issues with a specific version of AGP or Gradle, please reopen the issue and let us know which versions you’re using, or attach an example app.
